[build]
builder = "DOCKERFILE"
watchPatterns = ["app/**"]
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
# healthcheckPath = "helthcheck.php"
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10